version: "3"
services:
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  app:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/usr/src/app # Syncs local files with the container
      - /usr/src/app/node_modules # Prevents overwriting node_modules inside container
      - /usr/src/app/dist # Ensures compiled files remain updated
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      APP_PORT: ${SERVER_PORT}

    develop:
      watch:
        - action: sync
          path: ./web
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
